### ISSUE TITLE
release v1.1.0/v1.1.1 ?

### ISSUE THREAD

**Issue by mikanIchinose** [instantish/martian#11]
<sub>[Discuss in #**public-issue-11--release-v110v111-**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02Q4B2CLM6)</sub>

@instantish/martian latest version is `1.0.3`.
So I use @tryfabric/martian(`1.1.0`) instead of that.

**Comment by juliarosenson** [comment]
Hi @mikanIchinose moving forward updates will be published to @tryfabric/martian

**Comment by mikanIchinose** [comment]
Ok. I understand.
