### ISSUE TITLE
Latest version of Martian isn't published to NPM

### ISSUE THREAD

**Issue by rr-codes** [instantish/martian#13]
<sub>[Discuss in #**public-issue-13--latest-version-of-martian-isnt-published-to-npm**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02QAG1T1NY)</sub>

The NPM published version is v1.0.3, but the latest GH version is v1.1.1, so it should be updated on NPM too. :)

Awesome to see this package becoming relatively popular!!

**Comment by marissamarym** [comment]
hey richard! yes good point, we'll fix that so it's consistent for everyone. thanks!

**Comment by marissamarym** [comment]
we've moved all these packages under the `@tryfabric` npm org, so I'm going to update both packages, and add a note to the readme directing people to the `@tryfabric` one. the `@instantish` one is on 1.0.3, and the `@tryfabric` one is on 1.1.0.

open to any better solutions!

<img src="https://fabric-slack.s3.us-east-2.amazonaws.com/TJ5G67VHU/2eb0b0e0824ba883426bad4406d67473-screen_shot_2021-12-10_at_10.59.02_am.png" alt="screen_shot_2021-12-10_at_10.59.02_am.png" />
