### ISSUE TITLE
Simple table support

### ISSUE THREAD

**Issue by cliftonc** [instantish/martian#16]
<sub>[Discuss in #**public-issue-16--simple-table-support**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02T8PUAR8B)</sub>

https://developers.notion.com/changelog/simple-table-support 

This means that [the `unsupported` change](https://github.com/instantish/martian/blob/e662cf647fcc32d8c0cc7b294fe23f72b07eb01f/src/notion/blocks.ts#L153-L181) can be fixed!  I'll see if I can get it done some time this week unless it is already being worked on.

**Comment by marissamarym** [comment]
This would be great to have, thanks!
