### ISSUE TITLE
Equation block and inline math support

### ISSUE THREAD

**Issue by moeakwak** [instantish/martian#22]
<sub>[Discuss in #**public-issue-22--equation-block-and-inline-math-support**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C037Z15EEDC)</sub>

Thanks for the great package!

Martian seems not support math equations in markdown. For example:

```markdown
Lift($L$) can be determined by Lift Coefficient ($C_L$) like the following
equation.

$$
L = \frac{1}{2} \rho v^2 S C_L
$$
```

would be converted into plain text paragraph, keeping all `$` and `$$` symbols.

I found unified plugin `remark-math` may be useful. It would be amazing if Martian add support for math equations.

**Comment by marissamarym** [comment]
thanks for contributing! can you expand on what you mean by not supporting math equations? here’s a screenshot from something that uses this package and it looks like it matches how github renders the markdown

<img src="https://fabric-slack.s3.us-east-2.amazonaws.com/TJ5G67VHU/e37301d23a12577d06c0439fea78f64a-screen_shot_2022-03-22_at_1.22.25_pm.png" alt="screen_shot_2022-03-22_at_1.22.25_pm.png" />

**Comment by marissamarym** [comment]
oh sorry about that, I was switching from our repo that converts markdown into slack, and got confused. ok this makes sense, we can look into it
