### ISSUE TITLE
Deploy new nelease

### ISSUE THREAD

**Issue by tdurieux** [instantish/martian#26]
<sub>[Discuss in #**public-issue-26--deploy-new-nelease**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C039U1B48NL)</sub>

Hello,

Would it be possible to release the new version of the library to NPM?

Thank you very much for the library. It is really useful!

**Comment by marissamarym** [comment]
just pushed 1.2 (https://github.com/instantish/martian/releases/tag/v1.2.0). thanks!

**Comment by tdurieux** [comment]
Thank you!
