### ISSUE TITLE
Automatically bump version

### ISSUE THREAD

**Issue by juliarosenson** [instantish/martian#8]
<sub>[Discuss in #**public-issue-8--automatically-bump-version**](https://slack.com/app_redirect?team=TJ5G67VHU&channel=C02L4K9KJS1)</sub>

We could build our own action or I'm sure there are ones available in the marketplace that we could use to automatically bump the version in package.json when we cut releases

**Comment by marissamarym** [comment]
does `release-it` let us do that?
